### ISSUE TITLE
Structure view

### ISSUE THREAD

**Issue by craftey** [asciidoctor/asciidoctor-intellij-plugin#143]
AsciiDoc Plugin Version: 0.15.4
IDE Name and Version: 2016.2.4

A file which in ealier versions (<0.14) showed the correct structure view, does not show the structure view toc anymore.
Minimal non-working (no structure view) example

```
Test
====

== Foo

=== Bar
```

How ever the following works:

```
= Test

== Foo

=== Bar
```

Regards Craftey

**Comment by ahus1** [comment]
Thanks for reporting this. I'll look into this.

**Comment by mojavelinux** [comment]
I'd say this is correct. When using two-line section titles, the number of characters in the section title must match the number of characters in the underline. In the first example, that's not a valid document title.

**Comment by craftey** [comment]
@mojavelinux Ok, I will check if the issue persists, when numbers match. I will report back.

**Comment by craftey** [comment]
I tested with matching character count (4). Still the same issue. I modified the example in the original post.

**Comment by mojavelinux** [comment]
It's very likely two line section titles aren't implemented. Personally, I recommend against them.

**Comment by craftey** [comment]
Its just that one of the latest updates of the plugin removed the feature. It worked somewhen in the past, I am sure.

**Comment by ahus1** [comment]
I've looked into the older version and found the following given the example from above: 

```
Test
====

== Foo

=== Bar
```

Earlier versions (0.12) recognized "Foo" and "Bar" as headings, but never recognized "Test" as a heading.

Later versions introduced support for "Example Block Delimiters" when four or more equal signs (====) appear in a line with no other content.

Due to this version 0.13+ will treat everything below the four equal signs just after "Test" as an example block and will no longer recognize them as headings. 

I'm not sure yet how to update lexer and parser to recognize the four equal signs not as the begin of an example block.

**Comment by mojavelinux** [comment]
I would think it would just be a matter of checking for a trailing space followed by a word character. The example block can only have `=` on the line, nothing else.

**Comment by ahus1** [comment]
Hello Dmitry (aka @yole), 

some time ago you've contributed to syntax highlighting. This works well to create outlines, but I wonder how I can extend it to handle an alternative style of headings. 

I'd like to have you advice on how to handle a heading like this: 

````
Test
====
```

A line of text followed by the same amount of equal sign in the following line. The challenge is that the number of equal signs can also be the start of an example block when its number of equal signs doesn't match the number of characters of the headline.  

Can/Should that be handled in the asciidoc.flex (maybe with a forward rule) or should this be handled with Java logic inside of AsciiDocParserImpl.java? 

Thanks, 
Alexander aka @ahus1

**Comment by ahus1** [comment]
I've started working on this (see PR #146).

**Comment by craftey** [comment]
Hello again @ahus1  ,

I found some time to document some of my observations to clarify my issue.

The issue I initially wanted to report was not explicitly related to exactly 4 times '='.
I have a document with the following beginning

```
Migration Log
=============

== Preparations

=== Prepare empty DB

...
```

I reproduced today with version 0.12 this file shows the headline in preview and ignores the headine in structure view. (works for me)

When opening this file in version 0.13 and above this exact same file still renderes a nice preview but the structure view is empty despite the root node with the file name. I can see an error in the IntelliJ Event Log:
```
Unbalanced tree. Most probably caused by unbalanced markers. Try calling setDebugMode(true) against PsiBuilder passed to identify exact location of the problem
			language: Language: AsciiDoc, 
			context: ...
```

I hope this report explains my issue. I would at least expect that, like with v0.12, the structure view ignores the first headline `Migration Log` bit still shows the rest of the file headlines. Of cause better would be to render all headlines in structure view.

Kind Regards,
Craftey

**Comment by craftey** [comment]
**Update:** If I put a trailing space behind the last '=' of the first headline in my example, the the structure view is fixed. I use this as work arround for now.

**Comment by ahus1** [comment]
A preview release is available from the [github releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases). 

I'm keeping this ticket open to collect feedback. @craftey - please give it a try on your documents and provide examples where the parser doesn't fit yet.

**Comment by craftey** [comment]
@ahus1 Thanks for pinging me and your efforts. A first try with my files was ok. Preview and Structure view showed expected output.

Some Notes: 

1. CPU goes quite high here, when typing. Though also in java files cpu goes a little high. But writing ascii-doc seems to burn more cycles then usual.
2. A space after a '=' when using two-line section titles removes the headline from structure view and also changes color of the headline to normal text. I am OK with that since I strip trailing white space. Though could be improved.

**Comment by ahus1** [comment]
@craftey thank you for your feedback. I updated the parser to ignore white space at the end of the line. I'll post here once the new preview build is available.

**Comment by ahus1** [comment]
@mojavelinux Asciidoctor will strip the whitespace. But for the parser and the syntax highlighting the whitespace is still present... and needs to be handled.

**Comment by ahus1** [comment]
@craftey regarding CPU usage: most of the CPU usage will go into the asciidoc preview. For every change made in the document the full preview is re-rendered. You can save on CPU time when you hide the preview.

**Comment by ahus1** [comment]
Preview release 0.17.1 is now available from[ Github Releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases). Therefore I'm closing this ticket.

**Comment by craftey** [comment]
@mojavelinux I thought my .editorconfig File enables stripping whitespace in my project. If there is no .editorconfig then still there is a global setting in IntelliJ which defines trailing space stripping. Asciidoctor should not do it on its own, imho.

**Comment by mojavelinux** [comment]
You are correct to use .editorconfig to strip trailing white spaces as that sets the right expectation. Removing trailing white space is a critical part of the AsciiDoc syntax. That extends to source code included in AsciiDoc. (If you want to include content without this behavior, you need to create a custom include processor).
