### ISSUE TITLE
include of source code and "go to declaration"

### ISSUE THREAD

**Issue by luvarqpp** [asciidoctor/asciidoctor-intellij-plugin#320]
I do have some include source code in asciidoc documentation. Plugin renders them just fine, but "ctrl+click" shows that it "Cannot find declaration to go to".

```
Some sample java source code can be found here:
[source,java]
.Java code from tests to show how to get all TestThings
----
include::{testsourcedir}/sk/qpp/TestThingsRepositoryHttpTest.java[tags=getAllTestThingsSortedAndPaginatedDesc]
----
```

In .asciidoctorconfig file I have attribute defined: **:testsourcedir: {asciidoctorconfigdir}/src/test/java**. As render preview is OK, I think problem is not here.

Please add/fix functionality which makes "ctrl+click" on this type of include work.

AsciiDoc Plugin Version: 0.29.5

IDE Name and Version:
IntelliJ IDEA 2019.2 (Community Edition)
Build #IC-192.5728.98, built on July 23, 2019
Runtime version: 11.0.3+12-b304.10 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.0.0-23-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1910M
Cores: 8
Registry: git.explicit.commit.renames.prohibit.multiple.calls=false
Non-Bundled Plugins: DBN, Lombook Plugin, com.oliverlockwood.plugins.jenkinsfile, im.jeanfrancois.ideaplugins.ideafullscreen, manifold.ij, org.asciidoctor.intellij.asciidoc, com.intellij.lang.jsgraphql, org.intellij.scala, Docker, training

**Comment by luvarqpp** [comment]
Three collateral notices for code completion:

When I have written ```include::```, it offers me a list of files in current directory, including ".." directory, which I would expect to print "../", to be able to continue dir listing.

When I have written ```include::{tes}``` and I press ctrl+space to have some suggestions, it offers me tooltip with "no suggestions" text. I would expect at least to see attributes configured in .asciidoctorconfig file.

And the last "bells and whistles" category would be to have proper file list suggestions in scenario like this: ```include::{testsourcedir}/sk/```

**Comment by ahus1** [comment]
Unfortunately there was a parser bug that didn't allow for includes to be auto-completed within listings. I'm sorry for this, this is now fixed. 

Providing some additional automatic handling for "/" was on my list. This is now also implemented. 

When you type the path name, every "/" will close the auto completion and (if it is a directory you've chosen) open a new auto completion. When using tab to complete the selection, a "/" will be added for directories if a "/" doesn't follow the current auto completion item. Typing characters like "-" will no longer close the auto completion, neither will ".".

Attributes that complete to a valid path (and only those) will be automatically be part of the suggested list of files and directories. For these you don't need to type the "{" first.

![smart-include-path-complete](https://user-images.githubusercontent.com/3957921/63055271-d2817b00-bee5-11e9-929c-d74f824dcc08.gif)

This is all part of the pre-release 0.29.6. 
The new pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).

Please give it a try. As I was able to reproduce the issue locally and it now works for me, I close the issue. Please feel free to comment if I missed anything, and I'll repoen the issue again.

**Comment by luvarqpp** [comment]
@ahus1 thanks for very nice update.
I have tried it (right now), but seems not working for me. After writing `include::` and pressing alt+space, I see only files in current directory and not attribute.

I think that my problem is that I am using attribute in attribute, or something similar. If I add something like this `:testsourcedir2: /home/luvarqpp/` into .asciidoctorconfig file, it will list me given attribute.

Can you suggest me how to fix my set-up?

PS: I like attribute completion after writing `include::{`. It is so cool to have all information in single place.

**Comment by ahus1** [comment]
@luvarqpp - sorry, I've apparently closed this ticket too early. 

I've published 0.29.7 that now supports `asciidoctorconfigdir` properly. It will now be expanded in all places, also when using autocomplete for attribute references.

Please give 0.29.7 another try. I've tested this explicitly with a setup including `asciidoctorconfigdir`.

**Comment by luvarqpp** [comment]
@ahus1 seems better, but still one small improvement can be made...

When I write `include::`, there will be suggestions and if I choose attribute (which have value not ending by "/"), than I accept suggestion and it will look like this: `include::{testsourcedir}`, with suggestions opened, but only value of testsourcedir attribute is shown. No directory listing happens. When I add slas, it will look like this: `include::{testsourcedir}/` and everything is ok (suggestion with directories will came up).

**Comment by ahus1** [comment]
@luvarqpp - how do you select the entry? Using the keyboard (which key) or the mouse (what gesture/mouse button)?

**Comment by luvarqpp** [comment]
@ahus1 - I use keyboard, key enter. Output of xev utility to identify key:
```
KeyPress event, serial 33, synthetic NO, window 0x3800001,
    root 0x193, subw 0x0, time 453334539, (128,510), root:(1412,530),
    state 0x0, keycode 36 (keysym 0xff0d, Return), same_screen YES,
"   XLookupString gives 1 bytes: (0d) "
"   XmbLookupString gives 1 bytes: (0d) "
    XFilterEvent returns: False

KeyRelease event, serial 33, synthetic NO, window 0x3800001,
    root 0x193, subw 0x0, time 453334578, (128,510), root:(1412,530),
    state 0x0, keycode 36 (keysym 0xff0d, Return), same_screen YES,
"   XLookupString gives 1 bytes: (0d) "
    XFilterEvent returns: False
```

**Comment by luvarqpp** [comment]
Last release (0.29.8) works with enter like charm. Thanks.

Sidenote: original issue in this thread is still not working (ctrl+click on include word), but suggestion module have walked a long way. Should "ctrl+click" on include work now? (it is working through clicking on any path part, which focuses me on given path in project, or opens file if I ctrlClick on filename at the end).

One more unrelated suggestion improvement: adding suggestion for tags (I am not sure how is this feature called). I.e.: `include::{testsourcedir}/sk/qpp/TestAsdfHttpTest.java[` could list suggestion like `tags=requestHref`, when there is correct comment in given java file, like this:
```
// tag::requestHref[]
if(someSampleCode) {
    doSomething();
}
// end::requestHref[]
```

PS: My actual include is something like this:
```
----
include::{testsourcedir}/sk/qpp//TestAsdfHttpTest.java[tags=requestHref]
----
```
and I would love feature of ctrl+click on given tag (requestHref) to take me directly to given part of source code.

PS2: Sorry for confusion with unrelated things in first comment in this issue.

**Comment by ahus1** [comment]
@luvarqpp 

> it is working through clicking on any path part, which focuses me on given path in project, or opens file if I ctrlClick on filename at the end

This is the expected behavior. There is no plan to support click-in the `include::` part.

For supporting autocomplete for tags: please open a new issue for this.

Thank you for trying out the different releases. As autocomplete for files and navigation to the file works now, I close this issue.
