### ISSUE TITLE
Keyboard Navigation in Preview Only Mode

### ISSUE THREAD

**Issue by aeberts** [asciidoctor/asciidoctor-intellij-plugin#691]
## Why the new feature should be added

Currently there does not seem to be any way to scroll the document with the keyboard in "preview only" mode. In many cases, documents span many pages and it would be useful to be able to scroll the preview using space, down arrow, up arrow and page-up and page-down

## How the new feature should work

Current behaviour: pressing keys has no impact on the preview

Expected behaviour: 
- Pressing space scrolls the preview down by the same number of lines as Page-Down (like major browsers)
- Pressing the down arrow on the keyboard scrolls the preview down by one line 
- Pressing the up arrow on the keyboard scrolls the preview up by one line
- Pressing page-down scrolls the preview down by one page
- Pressing page-up scrolls the preview down by one page

**Comment by ahus1** [comment]
Thanks for suggesting this. I agree that this would be an improvement. 

It seems to be a focus problem: if you click on the preview with the mouse, the cursors work. 

I published pre-release 0.32.25 that should set the focus automatically to the preview if in preview-only mode. It works OK on Windows, but it seems to now have a focus problem on Linux. What OS are you using?

**Comment by aeberts** [comment]
Yes, agreed this seems to be a focus problem - I can confirm that after clicking in the window with the mouse the cursors do work.  I'm on MacOS running Intellij 2020.3

For reference, my workflow looks something like this:
- Type Shift-Shift to bring up the "search everywhere" window
- start typing in the name of the file (e.g. "Readme.adoc")
- Type "Enter" to select file -> the file opens in new tab with the tab name highlighted (the tab is *not* selected however and the cursor keys don't work)

Clicking the mouse in the preview window focuses the tab so that keyboard commands work correctly.

Ideally, I'd like to be able to navigate the preview window without using the mouse at all.

**Comment by ahus1** [comment]
The preview release 0.32.26 should support your workflow to some extent; at least the focus should go to the preview. 
There is another issue I found: it seems that IntelliJ is sometimes not returning the focus from the JCEF preview back to the editor correctly. You might need to use your mouse to return the focus to an editor. 

I can't test how this behaves on MacOS, please give it a try. 

From what I see the erroneous focus behavior is rooted in the IntelliJ platform. If you can reproduce the issue with the Markdown plugin, I suggest you open a YouTrack issue. Once that is fixed for Markdown, it will most likely work for AsciiDoc as well (or at least I will have some sample code to look at). 

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by aeberts** [comment]
Many thanks for the fix and the updated binary. I installed 0.32.26 and here's what I found testing on MacOS:

1) If Asciidoc is in preview mode and I open the file from the "search everywhere" window (shift-shift) the file opens and the tab is brought to the front and has the "blue underline" but the tab still doesn't have focus and the keyboard shortcuts do not work.
2) If I click in the preview window the tab gets focus and the keyboard shortcuts work correctly 
2b) If I do 1) above and then use the keyboard shortcut "Select Next Tab" and then, "Select Previous Tab" right after to re-select the AsciiDoc preview the tab correctly receives focus and the keyboard shortcuts are working (space, page-down, line-down, etc). 

2b is a decent workaround until Jetbrains fixes the tab focus issue (it may be fixed in the 2021 EAP but I can't upgrade at the moment). 

There are a number of "tab is not receiving focus" issues in the JetBrains YouTrack for Intellij. I have added a comment to say that this is still an issue on MacOS for both the bundled Markdown and AsciiDoc plugins:

https://youtrack.jetbrains.com/issue/IDEA-236257

My "About Intellij" for reference:

IntelliJ IDEA 2020.3.2 (Community Edition)
Build #IC-203.7148.57, built on January 25, 2021
Runtime version: 11.0.9.1+11-b1145.77 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.14.6
GC: ParNew, ConcurrentMarkSweep
Memory: 1998M
Cores: 6
Registry: documentation.show.toolbar=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: AceJump, Org4Idea, com.intellij.plugins.watcher, com.markskelton.one-dark-theme, name.kropp.intellij.makefile, String Manipulation, com.cursiveclojure.cursive, org.asciidoctor.intellij.asciidoc

**Comment by ahus1** [comment]
You actually found an issue that I opened some time ago :-) 

The situation might be a bit different as it assumes to assign custom shortcuts to the actions. Let's keep fingers crossed that this is being worked on at some point. 

Please consider using the "up-vote" functionality in YouTrack as well, not only commenting. Thanks!

**Comment by aeberts** [comment]
That's funny - I didn't notice that you were the original commenter! I've upvoted the item (and it's related issue) in YouTrack. I hope it will get fixed - for keyboard-centric folks it's pretty important! 

I'm happy to close this issue as it relates to asciidoctor. Many thanks for your help!

**Comment by ahus1** [comment]
Alright, let's close it. Once IntelliJ get's moving and this still a problem with the plugin, please comment here.
